pipeline:

  publish-image:
    image: plugins/docker
    repo: sebastianhutter/checkhttp
    dockerfile: Dockerfile
    tags:
      - "latest"
      - "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: [master]
